# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-View-Seamstress
version:      1.10
version_from: lib/Catalyst/View/Seamstress.pm
installdirs:  site
requires:
    Catalyst:                      5.5
    HTML::Seamstress:              0
    Template:                      0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
