--- #YAML:1.0
name:               Catalyst-View-Seamstress
version:            2.2_002
abstract:           ~
author:
    - Terrence Brannon (metaperl@gmail.com)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:          5.5
    HTML::Seamstress:  0
    Template:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
